# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('votes', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('W', 'Won'), ('C', 'Still Counting'), ('L', 'Lose')], max_length=1)),
                ('age', models.IntegerField()),
                ('criminalcase', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatyouweredoing', models.TextField()),
                ('whathappened', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ward', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.District')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('about', models.TextField()),
                ('established', models.DateField()),
                ('slogan', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('posted', models.DateField(auto_now=True)),
                ('home', models.CharField(choices=[('4', 'Defult'), ('1', 'Home 1'), ('2', 'Home 2'), ('3', 'Home 3')], default='4', max_length=1)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ward', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.District')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='vdc',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.Zone'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.Zone'),
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.Zone'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.District'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e2074.Municipality'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.Party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e2074.Vdc'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.Zone'),
        ),
    ]
