# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0002_post_auther'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politicaldiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.IntegerField(choices=[('1', 'Municipality'), ('2', 'Vdc')])),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.District')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e2074.Zone')),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='district',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='vdc',
            name='district',
        ),
        migrations.RemoveField(
            model_name='vdc',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vdc',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Vdc',
        ),
        migrations.AddField(
            model_name='candidate',
            name='politicaldiv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e2074.Politicaldiv'),
            preserve_default=False,
        ),
    ]
