# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0003_auto_20170422_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicaldiv',
            name='group',
            field=models.CharField(choices=[('1', 'Municipality'), ('2', 'Vdc')], max_length=1),
        ),
    ]
