# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0005_auto_20170423_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='birth',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
