# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0007_auto_20170426_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='metropolitan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='submetropolitan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
