# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0008_auto_20170426_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='criminalcase',
            field=models.IntegerField(verbose_name='No. of Criminal cases'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/photo'),
        ),
        migrations.AlterField(
            model_name='district',
            name='metropolitan',
            field=models.IntegerField(verbose_name='No. of metropolitan'),
        ),
        migrations.AlterField(
            model_name='district',
            name='municipality',
            field=models.IntegerField(verbose_name='No. of municipality'),
        ),
        migrations.AlterField(
            model_name='district',
            name='population',
            field=models.IntegerField(verbose_name='Total Population'),
        ),
        migrations.AlterField(
            model_name='district',
            name='submetropolitan',
            field=models.IntegerField(verbose_name='No. of sub-metropolitan'),
        ),
        migrations.AlterField(
            model_name='district',
            name='vdc',
            field=models.IntegerField(verbose_name='No. of VDC'),
        ),
        migrations.AlterField(
            model_name='district',
            name='voters',
            field=models.IntegerField(verbose_name='Total Voters'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='whathappened',
            field=models.TextField(verbose_name='What happended'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='whatyouweredoing',
            field=models.TextField(verbose_name='What you were doing'),
        ),
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.ImageField(upload_to='images/logo'),
        ),
    ]
