# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0009_auto_20170426_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='home',
            field=models.CharField(choices=[('4', 'Defult'), ('1', 'Home 1'), ('2', 'Home 2'), ('3', 'Home 3'), ('5', 'Top Section'), ('6', 'Bottom Section')], default='4', max_length=1, verbose_name='Choose Post Position'),
        ),
    ]
