# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0010_auto_20170426_1800'),
        ('e2074', '0009_auto_20170426_2139'),
    ]

    operations = [
    ]
