# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0010_auto_20170426_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('officialname', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('voters', models.IntegerField()),
                ('mvoters', models.IntegerField()),
                ('fvoters', models.IntegerField()),
                ('tgvoters', models.IntegerField()),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
