# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0011_merge_20170427_0614'),
        ('e2074', '0011_auto_20170427_0600'),
    ]

    operations = [
    ]
