# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0012_auto_20170427_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='officialname',
            field=models.CharField(max_length=100, verbose_name='Official Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='whathappened',
            field=models.TextField(verbose_name='What happened'),
        ),
    ]
