# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0012_auto_20170427_0623'),
        ('e2074', '0013_auto_20170427_1159'),
    ]

    operations = [
    ]
