# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0014_merge_20170427_1306'),
        ('e2074', '0014_auto_20170427_1241'),
    ]

    operations = [
    ]
