# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0015_merge_20170427_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='politicaldiv',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
