# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0016_auto_20170427_2328'),
        ('e2074', '0015_auto_20170427_1742'),
    ]

    operations = [
    ]
