# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0017_auto_20170428_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('1', 'Mayor'), ('2', 'Deputy Mayor'), ('3', 'Ward President'), ('4', 'Member')], default='4', max_length=1),
        ),
    ]
