# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e2074', '0017_auto_20170428_0841'),
        ('e2074', '0017_merge_20170427_2335'),
    ]

    operations = [
    ]
